
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17

    - name: Build Backend
      run: cd backend && mvn clean package -DskipTests

    - name: Build Frontend
      run: cd frontend && npm install && npm run build

    - name: Build Docker Images
      run: docker-compose build

    - name: Push to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker-compose push

    - name: Deploy to AWS
      run: ./deploy.sh
